const coloursArr = [
  'btn--deep-violet',
  'btn--grey',
  'btn--orange',
  'btn--yellow',
  'btn--green',
  'btn--purple',
  'btn--btn--teal',
  'btn--magenta',
  'btn--light-deep-violet',
  'btn--light-grey',
  'btn--light-orange',
  'btn--light-yellow',
  'btn--light-green',
  'btn--light-purple',
  'btn--light-teal',
  'btn--light-magenta',
  'btn--dark-deep-violet',
  'btn--dark-grey',
  'btn--dark-orange',
  'btn--dark-yellow',
  'btn--dark-green',
  'btn--dark-purple',
  'btn--dark-teal',
  'btn--dark-magenta',
];

export default coloursArr;
