language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

env:
  global:
    - SLS_DEBUG=true

script:
  - yarn eslint
  - yarn test

after_success:
  - yarn semantic-release
